#!/usr/bin/env python3
"""
Convert a single-sheet AKS Terraform design CSV to Terraform tfvars.

Input : design/AKS_Terraform_Design.csv
Output: env/dev.generated.tfvars

The CSV is expected to contain columns:
No, enabled, environment, domain, category, type, purpose,
param_01 ... param_20, terraform_stack, terraform_module, depends_on, owner, remarks
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path
from typing import Any, Dict


def as_bool(value: str) -> bool:
    return str(value).strip().lower() in {"true", "yes", "y", "1"}


def as_int(value: str, default: int = 0) -> int:
    value = str(value).strip()
    if value == "":
        return default
    return int(value)


def hcl_string(value: Any) -> str:
    if value is None:
        return "null"
    value = str(value)
    if value.lower() == "null":
        return "null"
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    return f'"{escaped}"'


def write_map(f, name: str, data: Dict[str, Dict[str, Any]]) -> None:
    f.write(f"{name} = {{\n")
    for key, values in data.items():
        f.write(f"  {hcl_string(key)} = {{\n")
        for k, v in values.items():
            if isinstance(v, bool):
                f.write(f"    {k} = {str(v).lower()}\n")
            elif isinstance(v, int):
                f.write(f"    {k} = {v}\n")
            elif isinstance(v, list):
                items = ", ".join(hcl_string(x) for x in v)
                f.write(f"    {k} = [{items}]\n")
            else:
                f.write(f"    {k} = {hcl_string(v)}\n")
        f.write("  }\n")
    f.write("}\n\n")


def convert(src: Path, dst: Path, env: str = "dev") -> None:
    namespaces: Dict[str, Dict[str, Any]] = {}
    apps: Dict[str, Dict[str, Any]] = {}
    pvcs: Dict[str, Dict[str, Any]] = {}
    helm_releases: Dict[str, Dict[str, Any]] = {}

    project_name = "aks-store-demo"
    prefix = "son01"
    location = "koreacentral"
    location_short = "krc"

    with src.open(newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if not as_bool(row.get("enabled", "false")):
                continue
            if row.get("environment", "").strip() not in {"", env}:
                continue

            domain = row.get("domain", "").strip()
            category = row.get("category", "").strip()
            rtype = row.get("type", "").strip()

            p1 = row.get("param_01", "").strip()
            p2 = row.get("param_02", "").strip()
            p3 = row.get("param_03", "").strip()
            p4 = row.get("param_04", "").strip()
            p5 = row.get("param_05", "").strip()
            p6 = row.get("param_06", "").strip()
            p7 = row.get("param_07", "").strip()

            if domain == "Common" and category == "Project":
                project_name = p1 or project_name
                prefix = p2 or prefix
                location = p3 or location
                location_short = p4 or location_short

            elif domain == "K8S" and category == "Namespace" and rtype == "namespace":
                namespaces[p1] = {
                    "enabled": True,
                    "name": p1,
                }

            elif domain == "K8S" and category == "App":
                app_name = p1
                apps[app_name] = {
                    "enabled": True,
                    "app_type": rtype,
                    "namespace": p2,
                    "image": p3,
                    "container_port": as_int(p4, 80),
                    "replicas": as_int(p5, 1),
                    "service_type": p6 or "ClusterIP",
                    "service_port": as_int(p7, as_int(p4, 80)),
                }

            elif domain == "K8S" and category == "Storage" and rtype == "pvc":
                pvc_name = p1
                pvcs[pvc_name] = {
                    "enabled": True,
                    "namespace": p2,
                    "storage_class": p3,
                    "size": p4,
                    "access_modes": [p5 or "ReadWriteOnce"],
                    "mount_path": p6,
                }

            elif domain == "CICD" and category == "Helm":
                release_name = p1
                helm_releases[release_name] = {
                    "enabled": True,
                    "namespace": p2,
                    "repository": p3,
                    "chart": p4,
                    "service_type": p5 or "ClusterIP",
                }

    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w", encoding="utf-8") as f:
        f.write("# Generated by tools/excel_to_tfvars.py\n")
        f.write("# Do not edit this file manually. Edit the Excel/CSV design file instead.\n\n")
        f.write(f"project_name   = {hcl_string(project_name)}\n")
        f.write(f"environment    = {hcl_string(env)}\n")
        f.write(f"location       = {hcl_string(location)}\n")
        f.write(f"location_short = {hcl_string(location_short)}\n")
        f.write(f"prefix         = {hcl_string(prefix)}\n\n")
        write_map(f, "namespaces", namespaces)
        write_map(f, "apps", apps)
        write_map(f, "persistent_volume_claims", pvcs)
        write_map(f, "helm_releases", helm_releases)


def main() -> int:
    if len(sys.argv) < 3:
        print("Usage: python3 tools/excel_to_tfvars.py <input.csv> <output.tfvars> [environment]", file=sys.stderr)
        return 1
    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    env = sys.argv[3] if len(sys.argv) >= 4 else "dev"
    convert(src, dst, env)
    print(f"Generated: {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
